from abc import ABC, abstractmethod
from simple_quant.events import OrderEvent

class ExecutionHandler(ABC):
    """
    The ExecutionHandler abstract class handles the interaction
    between a set of order objects generated by a Portfolio and
    the ultimate execution mechanism.

    The simulated execution handler simply converts all order
    objects into fill objects automatically at the current market
    prices (mocking). 

    A specific execution handler allows for API interaction 
    (e.g. IB, Interactive Brokers) or saving to a database.
    """

    @abstractmethod
    def execute_order(self, event: OrderEvent):
        """
        Takes an Order event and executes it, producing
        a Fill event that gets placed onto the Events queue.
        """
        raise NotImplementedError("Should implement execute_order()")
