from queue import Queue, Empty
from simple_quant.events import EventType
from simple_quant.data.base import DataHandler
from simple_quant.strategy.base import Strategy
from simple_quant.portfolio.base import Portfolio
from simple_quant.execution.base import ExecutionHandler
import time

class BacktestEngine:
    """
    Enscapsulates the settings and components for carrying out
    an event-driven backtest.
    """
    def __init__(
        self, 
        data_handler: DataHandler,
        strategy: Strategy,
        portfolio: Portfolio,
        execution_handler: ExecutionHandler,
        heartbeat: float = 0.0
    ):
        """
        Initializes the backtest.
        
        Parameters:
        data_handler - The DataHandler object to handle market data.
        strategy - The Strategy object to generate signals.
        portfolio - The Portfolio object to track positions and capital.
        execution_handler - The ExecutionHandler object to handle orders.
        heartbeat - Time in seconds to pause (simulates real-time if needed, usually 0 for backtest).
        """
        self.events = data_handler.events
        self.data_handler = data_handler
        self.strategy = strategy
        self.portfolio = portfolio
        self.execution_handler = execution_handler
        self.heartbeat = heartbeat
        
        self.signals = 0
        self.orders = 0
        self.fills = 0
        self.num_strats = 1

    def _run_backtest(self):
        """
        Executes the backtest.
        """
        print("Running Backtest...")
        while True:
            # Update the bars (this is the 'heartbeat' of the backtest)
            if self.data_handler.continue_backtest:
                self.data_handler.update_bars()
            else:
                break

            # Handle all events generated by the update_bars call
            while True:
                try:
                    event = self.events.get(block=False)
                except Empty:
                    break
                
                if event is not None:
                    if event.type == EventType.MARKET:
                        self.strategy.calculate_signals(event)
                        self.portfolio.update_timeindex(event)

                    elif event.type == EventType.SIGNAL:
                        self.signals += 1
                        self.portfolio.update_signal(event)

                    elif event.type == EventType.ORDER:
                        self.orders += 1
                        self.execution_handler.execute_order(event)

                    elif event.type == EventType.FILL:
                        self.fills += 1
                        self.portfolio.update_fill(event)

            time.sleep(self.heartbeat)
    
    def output_performance(self):
        """
        Outputs the strategy performance from the portfolio.
        """
        self.portfolio.create_equity_curve_dataframe()
        print("Creating summary stats...")
        stats = self.portfolio.output_summary_stats()
        print(stats)
        return stats

    def simulate_trading(self):
        """
        Simulates the backtest and outputs portfolio performance.
        """
        self._run_backtest()
        self.output_performance()
